"""
Project Euler Problem 12: Highly divisible triangular number

The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

import numpy as np

# Set minimum divisors.
divisorMin = 500

# Compute triangle number.
triangle = 1

# Initialise number of triangle number.
counter = 1

# Initialise variable for number of divisors.
divisors = 1

while divisors <= divisorMin:
    # Compute next triangle number, update counter.
    counter += 1
    triangle += counter

    # 1 is divisor, 0 is not divisor.
    divisorBinary = np.zeros(triangle+1)
    for i in range(triangle, 1, -1):
        # Deal with largest factors.
        if divisorBinary[i] == 0 and triangle % i == 0:
            divisorBinary[i] = 1

            # Deal with largest factors of factors.
            for j in range(i, 1, -1):
                if divisorBinary[j] == 0 and i % j == 0:
                    divisorBinary[j] = 1

    divisors = 0
    for b in np.nditer(divisorBinary):
        if b == 1:
            divisors += 1

# Divisors exceeded minimum number of divisors, output triangle number.
print(triangle)
